version: '3'

services:
  vrcbackend:
    image: vrcbackend:v1
    ports:
      - "3000:3000"
    environment:
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
      - ACCESS_TOKEN_SECRETKEY=${ACCESS_TOKEN_SECRETKEY}
      - REFRESH_TOKEN_SECRETKEY=${REFRESH_TOKEN_SECRETKEY}
