version: '3'

services:
  vrcbackend:
    image: vrcbackend:v1
    ports:
      - "4200:4200"
    environment:
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
      - ACCESS_TOKEN_SECRETKEY=${ACCESS_TOKEN_SECRETKEY}
      - REFRESH_TOKEN_SECRETKEY=${REFRESH_TOKEN_SECRETKEY}
      - EMAIL_API_KEY=${EMAIL_API_KEY}
      - EMAIL_SENDER=${EMAIL_SENDER}
      - RESET_BASE_URL=${RESET_BASE_URL}
    restart: always